openapi: 3.0.0
info:
  title: RTKIT HomeWork-4 Open API specification
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Dev server
paths:
  /:
    get:
      summary: Получение средних оценок каждого ученика в указанном классе
      parameters:
        - name: group
          in: query
          required: true
          description: Имя группы
          schema:
            type: string
        - name: limit
          in: query
          required: true
          description: Чисто элементов в ответе
          schema:
            type: integer
        - name: offset
          in: query
          required: true
          description: Чисто элементов, которые нужно пропустить при выдаче ответа
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsWhithAverage"
        'default':
          description: Все, что не ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    
    put:
      summary: Изменение оценки конкретного ученика по фамилии, имени, классу и конкретного предмета
      parameters:

        - name: family
          in: query
          required: true
          description: фамилия студента
          schema:
            type: string

        - name: name
          in: query
          required: true
          description: имя студента
          schema:
            type: string

        - name: group
          in: query
          required: true
          description: Имя группы
          schema:
            type: string

        - name: subject
          in: query
          required: true
          description: Имя учебного предмета
          schema:
            type: string

        - name: grade
          in: query
          required: true
          description: Новая оценка
          schema:
            type: integer
      
      responses:
        '200':
          description: OK
        'default':
          description: Все, что не ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    StudentsWhithAverage:
      type: array
      items:
        $ref: "#/components/schemas/StudentWhithAverage"
    
    StudentWhithAverage:
      type: object
      required:
        - family
        - name
        - group
        - average
      properties:
        family:
          type: string
          example: Иванов
        name:
          type: string
          example: Иван
        group:
          type: string
          example: "12"
        average:
          type: number
          example: 4.3
    
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Ничего не найдено"
          
    